# This file was generated by GoReleaser. DO NOT EDIT.
class Backlogboss < Formula
  desc "A contextual task manager to help developers finish their side projects."
  homepage "https://backlogboss.xyz"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/backlogboss/backlogboss/releases/download/v0.1.1/backlogboss_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "2316edfcfa95dcf7a0519f66596f65bcfadf5113851c89b5c782aa9a7ded39b4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/backlogboss/backlogboss/releases/download/v0.1.1/backlogboss_0.1.1_Linux_x86_64.tar.gz"
      sha256 "c41261f491524f78030d27a44fa2e036ffd46d990f904e84bc390349cf0584bf"
    end
  end

  def install
    bin.install "backlogboss"
  end

  test do
    system "#{bin}/backlogboss info"
  end
end
