# This file was generated by GoReleaser. DO NOT EDIT.
class Backlogboss < Formula
  desc "A contextual task manager to help developers finish their side projects."
  homepage "https://backlogboss.xyz"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/backlogboss/backlogboss/releases/download/v0.1.1/backlogboss_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "93c4858bb0956946d3bdbb0723110e9d2cf7906fd2e10c6b6ce422710066c303"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/backlogboss/backlogboss/releases/download/v0.1.1/backlogboss_0.1.1_Linux_x86_64.tar.gz"
      sha256 "92d97a400a38df1aaa699bc7b1942209e6586e114615be1d155727f9b97318e5"
    end
  end

  def install
    bin.install "backlogboss"
  end

  test do
    system "#{bin}/backlogboss info"
  end
end
